spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.6.160.236:9300,10.6.160.237:9300,10.6.160.238:9300


    hbase:
      quorum: 10.6.160.98,10.6.160.99,10.6.160.107
  datasource:
      druid:
        mysql:
          url: jdbc:mysql://10.5.32.85:3307/rp_mobeye_mktgo?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
          driver-class-name: com.mysql.jdbc.Driver
          username: mktgo
          password: dWbmVOOgNzIufLNT
          min-idle: 5
          initial-size: 5
          max-active: 20
          test-on-borrow: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.uuzu.mktgo.pojo
mapper:
  mappers:
    - com.uuzu.mktgo.config.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  #接口调试信息可以定义在这里
  info:
    contact:
      email: 798946620@qq.com
      phone: 15618947216